title = "Two Kearns Portfolio"
baseURL = "https://twokearns.netlify.app/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
email = "wolvesoftrash@gmail.com"
favicon = "/favicon.ico"
firstName = "Two"
lastName = "Kearns"
profileImage = "wolves_logo.png"
showQr = false
showContact = true
showBoards  = true
showCertifications = true
showSocializations = true
sections = ["about","resume","design","acting","experience","video production","information technology","directing","playwrighting"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/trashcanWolves"
    
[[params.handles]]
    name = "Bluesky"
    link = "https://bsky.app/profile/trashcanwolves.bsky.social"
    icon = "bluesky"


[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"